### 게시글 조회
GET http://localhost:3000/boards/1

### 게시글 리스트 조회
GET http://localhost:3000/boards?page=0&size=20

### 게시글 생성
POST http://localhost:3000/boards
Content-Type: application/json

{
  "title": "제목임",
  "content": "내용임"
}