### 로그인
POST http://localhost:3000/user/signin
Content-Type: application/json

{
  "email": "hkhong91@gmail.com",
  "password": "1234"
}

### 회원가입
POST http://localhost:3000/user/signup
Content-Type: application/json

{
  "name": "홍아지",
  "email": "hkhong91@gmail.com",
  "password": "1234",
  "gender": "MALE"
}

### 이메일 체크
GET http://localhost:3000/user/email/duplicate?email=hkhong91@gmail.com

### 이름 체크
GET http://localhost:3000/user/name/duplicate?name=홍아지