### 비디오 썸네일 리스트 조회
GET http://localhost:8080/videos

### 비디오 상세 조회
GET http://localhost:8080/videos/5fd097c10c31f908f7dc999a

### 비디오 등록
POST http://localhost:8080/videos
Content-Type: application/json

{
  "title": "[LIVE] SBS 8뉴스 - \"백신 4천4백만 명 분량 도입\"…언제 누구부터 맞을 수 있나? 外 12/8(화) | 모바일24",
  "thumbnail": "http://localhost:8080/img/8.jpg"
}